// <auto-generated />
using System;
using M133.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace M133.Migrations
{
    [DbContext(typeof(QuizletContext))]
    [Migration("20220405121807_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("M133.Models.Card", b =>
                {
                    b.Property<int>("CardId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CardId"), 1L, 1);

                    b.Property<string>("Definition")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StudySetId")
                        .HasColumnType("int");

                    b.Property<string>("Term")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CardId");

                    b.HasIndex("StudySetId");

                    b.ToTable("Cards");
                });

            modelBuilder.Entity("M133.Models.Learn", b =>
                {
                    b.Property<int>("LearnId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LearnId"), 1L, 1);

                    b.Property<int>("StudySetId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LearnId");

                    b.HasIndex("StudySetId");

                    b.HasIndex("UserId");

                    b.ToTable("Learns");
                });

            modelBuilder.Entity("M133.Models.LearnCard", b =>
                {
                    b.Property<int>("LearnCardId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LearnCardId"), 1L, 1);

                    b.Property<int>("CardId")
                        .HasColumnType("int");

                    b.Property<int>("LearnId")
                        .HasColumnType("int");

                    b.Property<int>("PoolId")
                        .HasColumnType("int");

                    b.Property<int>("RepeatedFalse")
                        .HasColumnType("int");

                    b.HasKey("LearnCardId");

                    b.HasIndex("CardId");

                    b.HasIndex("LearnId");

                    b.HasIndex("PoolId");

                    b.ToTable("LearnCards");
                });

            modelBuilder.Entity("M133.Models.Pool", b =>
                {
                    b.Property<int>("PoolId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PoolId"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PoolId");

                    b.ToTable("Pools");
                });

            modelBuilder.Entity("M133.Models.StudySet", b =>
                {
                    b.Property<int>("StudySetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StudySetId"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("StudySetId");

                    b.HasIndex("UserId");

                    b.ToTable("StudySets");
                });

            modelBuilder.Entity("M133.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"), 1L, 1);

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("M133.Models.Card", b =>
                {
                    b.HasOne("M133.Models.StudySet", "StudySet")
                        .WithMany("Cards")
                        .HasForeignKey("StudySetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StudySet");
                });

            modelBuilder.Entity("M133.Models.Learn", b =>
                {
                    b.HasOne("M133.Models.StudySet", "StudySet")
                        .WithMany("Learns")
                        .HasForeignKey("StudySetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("M133.Models.User", "User")
                        .WithMany("Learns")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StudySet");

                    b.Navigation("User");
                });

            modelBuilder.Entity("M133.Models.LearnCard", b =>
                {
                    b.HasOne("M133.Models.Card", "Card")
                        .WithMany("LearnCards")
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("M133.Models.Learn", "Learn")
                        .WithMany("LearnCards")
                        .HasForeignKey("LearnId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("M133.Models.Pool", "Pool")
                        .WithMany("LearnCards")
                        .HasForeignKey("PoolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Card");

                    b.Navigation("Learn");

                    b.Navigation("Pool");
                });

            modelBuilder.Entity("M133.Models.StudySet", b =>
                {
                    b.HasOne("M133.Models.User", "User")
                        .WithMany("StudySets")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("M133.Models.Card", b =>
                {
                    b.Navigation("LearnCards");
                });

            modelBuilder.Entity("M133.Models.Learn", b =>
                {
                    b.Navigation("LearnCards");
                });

            modelBuilder.Entity("M133.Models.Pool", b =>
                {
                    b.Navigation("LearnCards");
                });

            modelBuilder.Entity("M133.Models.StudySet", b =>
                {
                    b.Navigation("Cards");

                    b.Navigation("Learns");
                });

            modelBuilder.Entity("M133.Models.User", b =>
                {
                    b.Navigation("Learns");

                    b.Navigation("StudySets");
                });
#pragma warning restore 612, 618
        }
    }
}
